name: Auto-Clean

on:
  #自动清理：每周一早上4点
  schedule:
    - cron: 0 20 * * 0
  #手动清理
  workflow_dispatch:
    inputs:
      NUMBER:
        default: '8'
        required: false
        type: string

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: false
          releases_keep_latest: ${{inputs.NUMBER || '0'}}
          delete_tags: false
          delete_workflows: true
          workflows_keep_day: 0



